AWSTemplateFormatVersion: '2010-09-09'
Description: Template to deploy AWS Bedrock knowledge base and Lambda functions for API operations

Parameters:
  DocumentS3Key:
    Type: String
    Description: S3 key for the documents to ingest
  KnowledgeBaseID:
    Type: String
    Description: The Bedrock Knowledge base ID
    Default: ''
  LambdaLayerS3BucketName:
    Type: String
    Description: The S3 bucket stores lambda layer code
    Default: ''
  KnowledgeBaseBucketName:
    Type: String
    Description: The name of the existing S3 bucket for the Knowledge Base

Resources:
  # IAM Role for Bedrock Execution
  BedrockExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AmazonBedrockFoundationModelPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v
